# Generated by Django 6.0.6 on 2026-06-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='packages/'),
        ),
    ]
